from .aes import AESStream
from .ascon import AsconStream
from .serpent import SerpentStream
from .camellia import CamelliaStream
from .des3 import DES3Stream
from .chacha20 import ChaCha20Poly1305Stream, XChaCha20Poly1305Stream
from .salsa20 import Salsa20Stream
from .threefish import ThreefishSkeinMACStream
from .rsa import RSAOAEPStream, RSAPSSSigner
from .eddsa import EdDSASigner
from .ecdsa import ECDSASigner
from .ml_kem import MLKEMStream
from .ml_dsa import MLDSASigner
from .slh_dsa import SLHDSASigner


ALGORITHMS = {
    "AES": {
        "implementation": AESStream,
        "type": "symmetric",
        "standard": "NIST FIPS 197",
        "family": "block-cipher",
        "status": "standardized",
        "key_lengths": [256, 192, 128],
        "mode_key_lengths": {
            "SIV (AEAD)": [512, 384, 256],
        },
        "modes": [
            "GCM (AEAD)",
            "EAX (AEAD)",
            "SIV (AEAD)",
            "CCM (AEAD)",
            "OCB (AEAD)",
            "CTR",
            "CBC",
            "ECB",
        ],
        "mode_streaming": {
            "GCM (AEAD)": True,
            "EAX (AEAD)": True,
            "SIV (AEAD)": False,
            "CCM (AEAD)": False,
            "OCB (AEAD)": False,
            "CTR": True,
            "CBC": True,
            "ECB": True,
        },
    },
    "ASCON": {
        "implementation": AsconStream,
        "type": "symmetric",
        "standard": "NIST SP 800-232",
        "family": "lightweight-aead",
        "status": "standardized",
        "key_lengths": [128],
        "modes": ["Ascon-128 (AEAD)"],
        "mode_streaming": {"Ascon-128 (AEAD)": True},
    },
    "Serpent-HMAC": {
        "implementation": SerpentStream,
        "type": "symmetric",
        "standard": "AES finalist / custom Encrypt-then-MAC",
        "family": "block-cipher-etm",
        "status": "non-standardized",
        "key_lengths": [256, 192, 128],
        "modes": ["CBC + HMAC-SHA256"],
        "mode_streaming": {"CBC + HMAC-SHA256": True},
    },
    "Camellia": {
        "implementation": CamelliaStream,
        "type": "symmetric",
        "standard": "RFC 3713 / ISO/IEC 18033-3",
        "family": "block-cipher",
        "status": "standardized",
        "key_lengths": [256, 192, 128],
        "modes": ["CFB", "CBC"],
        "mode_streaming": {
            "CFB": True,
            "CBC": True,
        },
    },
    "3DES": {
        "implementation": DES3Stream,
        "type": "symmetric",
        "standard": "NIST SP 800-67 (withdrawn)",
        "family": "block-cipher",
        "status": "legacy",
        "key_lengths": [192],
        "modes": ["EAX (AEAD)", "CTR", "CFB", "OFB"],
        "mode_streaming": {
            "EAX (AEAD)": True,
            "CTR": True,
            "CFB": True,
            "OFB": True,
        },
    },
    "ChaCha20-Poly1305": {
        "implementation": ChaCha20Poly1305Stream,
        "type": "symmetric",
        "standard": "RFC 8439",
        "family": "stream-aead",
        "status": "specified",
        "key_lengths": [256],
        "streaming": True,
    },
    "XChaCha20-Poly1305": {
        "implementation": XChaCha20Poly1305Stream,
        "type": "symmetric",
        "standard": "draft-irtf-cfrg-xchacha",
        "family": "stream-aead",
        "status": "non-standardized",
        "key_lengths": [256],
        "streaming": True,
    },
    "Salsa20": {
        "implementation": Salsa20Stream,
        "type": "symmetric",
        "standard": "eSTREAM Portfolio",
        "family": "stream-cipher",
        "status": "portfolio",
        "key_lengths": [256],
        "streaming": True,
    },
    "Threefish-Skein-MAC": {
        "implementation": ThreefishSkeinMACStream,
        "type": "symmetric",
        "standard": "Skein SHA-3 finalist",
        "family": "tweakable-block-cipher-mac",
        "status": "non-standardized",
        "key_lengths": [1024, 512, 256],
        "streaming": True,
    },
    "RSA-OAEP": {
        "implementation": RSAOAEPStream,
        "type": "asymmetric",
        "standard": "PKCS #1 v2.2 / RFC 8017",
        "family": "rsa-encryption",
        "status": "specified",
        "key_lengths": [4096, 3072, 2048],
        "hashes": [
            "SHA3-512",
            "SHA3-384",
            "SHA3-256",
            "SHA-512",
            "SHA-384",
            "SHA-256",
        ],
        "streaming": True,
    },
    "RSA-PSS": {
        "implementation": RSAPSSSigner,
        "type": "asymmetric",
        "standard": "NIST FIPS 186-5 / RFC 8017",
        "family": "rsa-signature",
        "status": "standardized",
        "key_lengths": [4096, 3072, 2048],
        "hashes": [
            "SHA3-512",
            "SHA3-384",
            "SHA3-256",
            "SHA-512",
            "SHA-384",
            "SHA-256",
        ],
        "streaming": True,
    },
    "EdDSA": {
        "implementation": EdDSASigner,
        "type": "asymmetric",
        "standard": "RFC 8032",
        "family": "edwards-curve-signature",
        "status": "specified",
        "curves": ["Ed25519", "Ed448"],
        "streaming": True,
    },
    "ECDSA": {
        "implementation": ECDSASigner,
        "type": "asymmetric",
        "standard": "NIST FIPS 186-5",
        "family": "elliptic-curve-signature",
        "status": "standardized",
        "curves": [
            "P-521 (secp521r1)",
            "P-384 (secp384r1)",
            "P-256 (secp256r1)",
        ],
        "hashes": [
            "SHA3-512",
            "SHA3-384",
            "SHA3-256",
            "SHA-512",
            "SHA-384",
            "SHA-256",
        ],
        "streaming": True,
    },
    "ML-KEM": {
        "implementation": MLKEMStream,
        "type": "asymmetric",
        "standard": "NIST FIPS 203",
        "family": "module-lattice-kem",
        "status": "standardized",
        "parameter_sets": [
            "ML-KEM-1024",
            "ML-KEM-768",
            "ML-KEM-512",
        ],
        "streaming": True,
    },
    "ML-DSA": {
        "implementation": MLDSASigner,
        "type": "asymmetric",
        "standard": "NIST FIPS 204",
        "family": "module-lattice-signature",
        "status": "standardized",
        "parameter_sets": [
            "ML-DSA-87",
            "ML-DSA-65",
            "ML-DSA-44",
        ],
        "streaming": False,
    },
    "SLH-DSA": {
        "implementation": SLHDSASigner,
        "type": "asymmetric",
        "standard": "NIST FIPS 205",
        "family": "hash-based-signature",
        "status": "standardized",
        "parameter_sets": [
            "SLH-DSA-SHAKE-256s",
            "SLH-DSA-SHAKE-256f",
            "SLH-DSA-SHA2-256s",
            "SLH-DSA-SHA2-256f",
            "SLH-DSA-SHAKE-192s",
            "SLH-DSA-SHAKE-192f",
            "SLH-DSA-SHA2-192s",
            "SLH-DSA-SHA2-192f",
            "SLH-DSA-SHAKE-128s",
            "SLH-DSA-SHAKE-128f",
            "SLH-DSA-SHA2-128s",
            "SLH-DSA-SHA2-128f",
        ],
        "streaming": False,
    },
}